name: Traffic Density CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute notebook
      run: |
        pip install nbconvert nbformat jupyter
        jupyter nbconvert --to notebook --execute traffic-density-estimation-with-yolov8.ipynb --output executed_notebook.ipynb
